version: "3.8"

services:
  mysql_cliente:
    image: mysql
    container_name: "microservicio-cliente"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: clientes