version: "3.8"

services:
  db-mongo:
    container_name: microservicio-parada
    image: mongo
    command:
      - --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: paradas
    volumes:
      - ./init-mongo:/docker-entrypoint-initdb.d/
    ports:
      - "127.0.0.1:27017:27017"
